In [2]:
import numpy as np
A = np.array([[4,1,1,4],
             [0,4,2,0],
             [2,0,4,5],
             [1,4,0,1]])

In [11]:
# Euclidean Distance_1
def EUC1(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    for u in range(0, NumUsers):
        for v in range(0, NumUsers):
            tmp = np.sum(np.square(a[u,]-a[v,]))
            Sim[u,v] = Sim[v,u] = np.sqrt(tmp)
    return Sim

In [12]:
EUC1(A)

array([[0.        , 6.4807407 , 3.87298335, 5.29150262],
       [6.4807407 , 0.        , 7.        , 2.44948974],
       [3.87298335, 7.        , 0.        , 7.        ],
       [5.29150262, 2.44948974, 7.        , 0.        ]])

In [9]:
# Euclidean Distance_2
def EUC2(u,v):
    tmp = np.sum(np.square(u-v))
    Sim = np.sqrt(tmp)
    return Sim

In [10]:
EUC2(A[0,],A[2,])

3.872983346207417

In [17]:
# Jaccard Measure_1
def JAC1(u,v):
    U = np.array(u>0, dtype=np.int) # rating -> binary
    V = np.array(v>0, dtype=np.int)
    tmp = U+V
    Inter = np.sum(np.array(tmp>1, dtype = np.int))
    Union = np.sum(np.array(tmp>0, dtype = np.int))
    return Inter/Union

In [18]:
JAC1(A[0,],A[2,])

/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/3661156930.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  U = np.array(u>0, dtype=np.int) # rating -> binary
/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/3661156930.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to re

0.75

In [19]:
# Jaccard Measure_2
def JAC2(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    for u in range(0, NumUsers):
        for v in range(0, NumUsers):
            U = np.array(a[u,]>0, dtype=np.int) # rating -> binary
            V = np.array(a[v,]>0, dtype=np.int)
            SumUV = U+V
            Inter = np.sum(np.array(SumUV>1, dtype = np.int))
            Union = np.sum(np.array(SumUV>0, dtype = np.int))
            tmp = Inter/Union
            Sim[u,v] = tmp
            Sim[v,u] = Sim[u,v]
    return Sim

In [21]:
JAC2(A)

/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/2828486174.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  U = np.array(a[u,]>0, dtype=np.int) # rating -> binary
/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/2828486174.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish t

array([[1.  , 0.5 , 0.75, 0.75],
       [0.5 , 1.  , 0.25, 0.25],
       [0.75, 0.25, 1.  , 0.5 ],
       [0.75, 0.25, 0.5 , 1.  ]])

In [30]:
# Mean Squared Difference_1
def MSD1(u,v):
    U = np.where(u==0, np.nan, u) # conver 0 -> nan
    V = np.where(v==0, np.nan, v)
    SquaredSum = np.square(U-V)
    SquaredSum = SquaredSum[~np.isnan(SquaredSum)] # remove nan value
    
    Allitems = np.size(SquaredSum, axis=0)
    tmp = np.sum(SquaredSum)/Allitems
    return tmp

In [31]:
MSD1(A[0,],A[2,])

3.75

In [34]:
# Mean Squared Difference_2
def MSD2(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    for u in range(0, NumUsers):
        for v in range(0, NumUsers):
            U = np.where(a[u,]==0, np.nan, a[u,])
            V = np.where(a[v,]==0, np.nan, a[v,])
            SquaredSum = np.square(U-V)
            SquaredSum = SquaredSum[~np.isnan(SquaredSum)] # remove nan value
            
            Allitems = np.size(SquaredSum, axis=0)
            tmp = np.sum(SquaredSum)/Allitems
    
            Sim[u,v] = tmp
            Sim[v,u] = Sim[u,v]
    return Sim

In [35]:
MSD2(A)

array([[0.        , 5.        , 4.66666667, 9.        ],
       [5.        , 0.        , 4.        , 0.        ],
       [4.66666667, 4.        , 0.        , 8.5       ],
       [9.        , 0.        , 8.5       , 0.        ]])

In [37]:
#JMSD_1
def JMSD1(u,v,max):
    return JAC1(u,v)*(1-(MSD1(u/max, v/max)))
JMSD1(A[0,],A[2,],5)

/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/3661156930.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  U = np.array(u>0, dtype=np.int) # rating -> binary
/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/3661156930.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to re

0.6375

In [38]:
#JMSD_1
def JMSD2(a,max):
    return JAC2(a)*(1-(MSD2(a/max)))
JMSD2(A,5)

/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/2828486174.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  U = np.array(a[u,]>0, dtype=np.int) # rating -> binary
/var/folders/1m/c6k1f_pd4vx1v_sj8708f_jw0000gn/T/ipykernel_55463/2828486174.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish t

array([[1.  , 0.4 , 0.61, 0.48],
       [0.4 , 1.  , 0.21, 0.25],
       [0.61, 0.21, 1.  , 0.33],
       [0.48, 0.25, 0.33, 1.  ]])