In [2]:
import numpy as np
A = np.array([[4,1,1,4],
             [0,4,2,0],
             [2,0,4,5],
             [1,4,0,1]])

In [5]:
# cosine similarity_1
def COS1(u,v):
    return np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))

In [6]:
COS1(A[0,],A[2,])

0.8180959881038617

In [9]:
# cosine similarity_2
def COS2(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    
    for u in range(0, NumUsers):
        for v in range(0, NumUsers):
            InnerDot = np.dot(a[u,],a[v,])
            NormU = np.linalg.norm(a[u,])
            NormV = np.linalg.norm(a[v,])
            Sim[u,v] = Sim[v,u] = InnerDot / (NormU * NormV)
    return Sim

In [10]:
COS2(A)

array([[1.        , 0.2300895 , 0.81809599, 0.48507125],
       [0.2300895 , 1.        , 0.26666667, 0.84327404],
       [0.81809599, 0.26666667, 1.        , 0.24595493],
       [0.48507125, 0.84327404, 0.24595493, 1.        ]])

In [13]:
# cosine similarity withour null_1
def NCOS1(u,v):
    u = A[0,]
    v = A[2,]
    arridx_u = np.where(u==0)
    arridx_v = np.where(v==0)
    arridx = np.concatenate((arridx_u, arridx_v), axis=None) # find null value

    U = np.delete(u, arridx)
    V = np.delete(v, arridx)
    return np.dot(U,V) / (np.linalg.norm(U)*np.linalg.norm(V))

In [14]:
NCOS1(A[0,],A[2,])

0.830398873772291

In [15]:
# cosine similarity withour null_1
def NCOS2(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    
    for u in range(0, NumUsers):
        for v in range(0, NumUsers):
            arridx_u = np.where(a[u,] == 0)
            arridx_v = np.where(a[v,] == 0)
            arridx = np.concatenate((arridx_u, arridx_v), axis=None)
            
            U = np.delete(a[u,], arridx)
            V = np.delete(a[v,], arridx)
            
            InnerDot = np.dot(U,V)
            NormU = np.linalg.norm(U)
            NormV = np.linalg.norm(V)
            Sim[u,v] = Sim[v,u] = InnerDot / (NormU * NormV)
    return Sim

In [16]:
NCOS2(A)

array([[1.        , 0.9486833 , 0.83039887, 0.49236596],
       [0.9486833 , 1.        , 1.        , 1.        ],
       [0.83039887, 1.        , 1.        , 0.91914503],
       [0.49236596, 1.        , 0.91914503, 1.        ]])

In [19]:
# pearson correlation coefficient_1
def PCC1(u,v):
    U_mean = np.nanmean(np.where(u!=0,u,np.nan))
    V_mean = np.nanmean(np.where(v!=0,v,np.nan))
    
    arridx_u = np.where(u==0)
    arridx_v = np.where(v==0)
    arridx = np.concatenate((arridx_u, arridx_v), axis=None) # find null value

    U = np.delete(u, arridx)
    V = np.delete(v, arridx)
    U = U-U_mean
    V = V-V_mean
    
    return np.dot(U,V) / (np.linalg.norm(U)*np.linalg.norm(V))

In [20]:
PCC1(A[0,],A[2,])

-0.1781741612749495

In [21]:
# pearson correlation coefficient_2
def PCC2(a):
    NumUsers = np.size(a, axis=0)
    Sim = np.full((NumUsers, NumUsers), 0.0)
    
    mean = np.nanmean(np.where(a!=0, a, np.nan), axis = 1)
    
    for u in range(0, NumUsers):
        for v in range(u, NumUsers):
            arridx_u = np.where(a[u,] == 0)
            arridx_v = np.where(a[v,] == 0)
            arridx = np.concatenate((arridx_u, arridx_v), axis=None)
            
            U = np.delete(a[u,], arridx)
            V = np.delete(a[v,], arridx)
            U = U-mean[u]
            V = V-mean[v]
            
            InnerDot = np.dot(U,V)
            NormU = np.linalg.norm(U)
            NormV = np.linalg.norm(V)
            Sim[u,v] = Sim[v,u] = InnerDot / (NormU * NormV)
    return Sim

In [22]:
PCC2(A)

array([[ 1.        ,  0.        , -0.17817416, -0.94280904],
       [ 0.        ,  1.        , -1.        ,  1.        ],
       [-0.17817416, -1.        ,  1.        ,  0.11043153],
       [-0.94280904,  1.        ,  0.11043153,  1.        ]])