In [2]:
docs = [
    '먹고 싶은 사과',  # 문서0
    '먹고 싶은 바나나',  # 문서1
    '길고 노란 바나나 바나나', # 문서2
    '저는 과일이 좋아요'  # 문서3
]
docs

['먹고 싶은 사과', '먹고 싶은 바나나', '길고 노란 바나나 바나나', '저는 과일이 좋아요']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [5]:
countvect = vect.fit_transform(docs)
countvect # 4*9 : 4개의 문서, 9개의 단어

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [6]:
# sparse matrix -> numpy 형태로 바꿈
# but, 각 index, columns이 무엇을 의미하는지 알 수 없음
countvect.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]])

In [9]:
# 각 column명을 알 수 있음
vect.vocabulary_

{'먹고': 3,
 '싶은': 6,
 '사과': 5,
 '바나나': 4,
 '길고': 1,
 '노란': 2,
 '저는': 7,
 '과일이': 0,
 '좋아요': 8}

In [10]:
sorted(vect.vocabulary_)

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [12]:
import pandas as pd
countvect_df = pd.DataFrame(countvect.toarray(), columns=sorted(vect.vocabulary_))
countvect_df.index = ['문서1','문서2','문서3','문서4']
countvect_df

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
문서1    0   0   0   1    0   1   1   0    0
문서2    0   0   0   1    1   0   1   0    0
문서3    0   1   1   0    2   0   0   0    0
문서4    1   0   0   0    0   0   0   1    1

In [13]:
# 위의 DataFrame형태의 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(countvect_df, countvect_df) 

## 결과 해석 : 문서1-문서2 유사, 문서2-문서3 유사

array([[1.        , 0.66666667, 0.        , 0.        ],
       [0.66666667, 1.        , 0.47140452, 0.        ],
       [0.        , 0.47140452, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [17]:
# TF-IDF vector : 의미없는 데이터(조사 등)을 제거할 수 있음
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
tfvect = vect.fit(docs)

TfidfVectorizer()

In [18]:
tfidv_df = pd.DataFrame(tfvect.transform(docs).toarray(), columns=sorted(vect.vocabulary_))
tfidv_df.index = ['문서1','문서2','문서3','문서4']
tfidv_df

과일이       길고       노란        먹고      바나나        사과        싶은  \
문서1  0.00000  0.00000  0.00000  0.526405  0.00000  0.667679  0.526405   
문서2  0.00000  0.00000  0.00000  0.577350  0.57735  0.000000  0.577350   
문서3  0.00000  0.47212  0.47212  0.000000  0.74445  0.000000  0.000000   
문서4  0.57735  0.00000  0.00000  0.000000  0.00000  0.000000  0.000000   

          저는      좋아요  
문서1  0.00000  0.00000  
문서2  0.00000  0.00000  
문서3  0.00000  0.00000  
문서4  0.57735  0.57735

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfidv_df, tfidv_df) 

array([[1.        , 0.60784064, 0.        , 0.        ],
       [0.60784064, 1.        , 0.42980824, 0.        ],
       [0.        , 0.42980824, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])